

#primary datasource
#spring.datasource.primary.jdbc.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.primary.jdbc.url=jdbc:mysql://127.0.0.1:3306/mysql_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
#spring.datasource.primary.jdbc.username=root
#spring.datasource.primary.jdbc.password=root
#spring.datasource.primary.initialSize=5
#spring.datasource.primary.maxActive=10
#spring.datasource.primary.minIdle=1
#spring.datasource.primary.maxWait=30000
#spring.datasource.primary.validationQuery=SELECT '1'
#spring.datasource.primary.testOnBorrow=false
#spring.datasource.primary.testOnReturn=false
#spring.datasource.primary.testWhileIdle=true
#spring.datasource.primary.poolPreparedStatements=false
#spring.datasource.primary.maxOpenPreparedStatements=-1
#spring.datasource.primary.org.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
#spring.datasource.primary.hibernate.show_sql=true


spring:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/mysql_test?rewriteBatchedStatements=true
      username: root
      password: 123456
    secondary:
      url: jdbc:mysql://localhost:3306/mysql_test?rewriteBatchedStatements=true
      username: root
      password: 123456
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy